/*
 *  UCF COP3330 Fall 2021 Assignment 4 Solutions
 *  Copyright 2021 Joshua Davis
 */

@startuml
'https://plantuml.com/sequence-diagram

Class Solution42{
    main(String[])
    ' FileScanner fs = new FileScanner()
    ' fs.readFile
    ' fs.printData
}

Class FileScanner{
    -List<String> employeeFNames
    -List<String> employeeLNames
    -List<string> employeeSalary

    +readFile(String filename)
    +printData()
    +getFNames()
}
Solution42 --o FileScanner
@enduml
