@startuml
'https://plantuml.com/sequence-diagram

Class Solution43{
    +main(String[])
    ' Instantiate website generator.
    ' Call the folderCreator method and Website generator will take care of the rest.
}

Class WebsiteGenerator{
    -String jsAns
    -String cssAns
    -String author
    -String site
    -String createdConstant
    +WebsiteGenerator()
    +folderCreator()
    -indexCreator()
}

Solution43 --o WebsiteGenerator
@enduml