@startuml
'https://plantuml.com/sequence-diagram
Class Solution46{
    +main(String[])
}

Class WordFrequency{
    -uniqueWords
    -entireFile
    -filePathString
    +readFile():List<String>
    +frequencyCounter(String):int
    +uniqueWordListCretaor():List<String>
    +processOutput()
}

Solution46 --o WordFrequency

@enduml